title: Hello, World! I’m Abdul - AI Enthusiast & Code Whisperer
description: Abdul Homepage
baseurl: ""
url: "https://sabdulrahman.github.io/"

# site settings
taglong: "<p>Ever since I typed my very first line of code, I've been captivated by the endless potential of technology to shape our world. Today, as a computer scientist and PhD candidate at Northern Illinois University, I focus on harnessing AI, LLMs, and other cutting-edge tools to tackle complex problems and drive meaningful change. By bridging theoretical research with practical applications, I'm working to make complex systems more efficient, scalable, and impactful.</p>
<p>Here, you’ll find my latest projects, insights, and collaborative endeavors aimed at pushing technology forward. Whether you’re seeking fresh inspiration or eager to dive into groundbreaking discussions, let’s connect and explore the possibilities!</p>"
tagshort: Homepage

# author settings
author:
  name: Abdul Rahman Shaikh
  email: iamsabdurahman@gmail.com
photo: assets/files/photo.jpeg
address:
phone: +1 224 848 8888


# social media links
social:
  facebook: username
  github: sabdulrahman
  instagram: iamabdurahman
  linkedin: iamsabdurahman
  stackoverflow: 0000000/username
  x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md


navs:
  - href: /resume
    label: Resume

  - href: '#research'
    label: Research

  - href: '#project'
    label: Projects

  - href: '#contact'
    label: Contact