title: Hello, World! I’m Abdul - AI Enthusiast, Code Whisperer
description: Abdul Homepage
baseurl: ""
url: https://sabdulrahman.github.io/

# site settings
taglong: <p>I’m a passionate technologist and final-year Computer Science PhD candidate specializing in leveraging AI, large language models, and cutting-edge technologies to solve complex challenges. From crafting AI that might take over the world (just kidding!) to building scalable software, I’m dedicated to creating meaningful impact through tech and collaboration.</p>
  <p>Here, you’ll find my projects, insights, and contributions to the tech community. 
  Whether you’re looking for collaboration, inspiration, or just want to discuss groundbreaking ideas, let’s connect and explore the possibilities together!</p>
tagshort: Homepage

# author settings
author:
  name: Abdul Rahman Shaikh
  email: iamsabdurahman@gmail.com
photo: assets/files/photo.jpeg
address:
phone: +1 224 848 8888

# social media links
social:
  facebook: username
  github: sabdulrahman
  instagram: username
  linkedin: username
  stackoverflow: 0000000/username
  x: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md


navs:
  - href: /resume
    label: Resume

  - href: '#research'
    label: Research

  - href: '#project'
    label: Projects

  - href: '#contact'
    label: Contact